language: python
python:
  - "3.6"
env: # => 4    
  -DJANGO=1.8
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python run manage.py test
after_success:
  coveralls
